#!/bin/bash
 
sudo rm -f   libboost_atomic.so.1.59.0 
sudo rm -f   libboost_system.so.1.59.0 
sudo rm -f   libboost_thread.so.1.59.0 
sudo rm -f   libboost_timer.so.1.59.0 
sudo rm -f   libboost_program_options.so.1.59.0 
sudo rm -f   libboost_locale.so.1.59.0 
sudo rm -f   libboost_iostreams.so.1.59.0 
sudo rm -f   libboost_filesystem.so.1.59.0 
sudo rm -f   libboost_date_time.so.1.59.0 
sudo rm -f   libboost_regex.so.1.59.0 
sudo rm -f    libboost_chrono.so.1.59.0 
sudo rm -f    libfreeimage.so 
sudo rm -f    libsoci_core.so.3.0.0 
sudo rm -f    libsoci_sqlite3.so.3.0.0 
sudo rm -f    libiconv.so.2 
sudo rm -f    libjemalloc.so.1 
sudo rm -f    libminiupnpc.so.10 
sudo rm -f    libnatpmp.so.1 
sudo rm -f    libopencv_imgproc.so.2.4 
sudo rm -f    libopencv_core.so.2.4 
sudo rm -f    liblrc.so.0 
sudo rm -f   libgnsdk_correlates.so.3.07.7 
sudo rm -f    libgnsdk_dsp.so.3.07.7 
sudo rm -f    libgnsdk_fp.so.3.07.7 
sudo rm -f    libgnsdk_link.so.3.07.7 
sudo rm -f    libgnsdk_lookup_local.so.3.07.7 
sudo rm -f    libgnsdk_lookup_localstream.so.3.07.7 
sudo rm -f    libgnsdk_manager.so.3.07.7 
sudo rm -f    libgnsdk_moodgrid.so.3.07.7 
sudo rm -f    libgnsdk_musicid_file.so.3.07.7 
sudo rm -f    libgnsdk_musicid.so.3.07.7 
sudo rm -f    libgnsdk_musicid_match.so.3.07.7 
sudo rm -f    libgnsdk_musicid_stream.so.3.07.7 
sudo rm -f    libgnsdk_playlist.so.3.07.7 
sudo rm -f    libgnsdk_rhythm.so.3.07.7 
sudo rm -f    libgnsdk_storage_sqlite.so.3.07.7 
sudo rm -f    libgnsdk_submit.so.3.07.7 /usrlib
sudo rm -f    libgnsdk_submit.so.3.07.7 
sudo rm -f    libgnsdk_tocgen.so.3.07.7 
sudo rm -f    libgnsdk_video.so.3.07.7 
