######################################################################
# Automatically generated by qmake (3.1) Sun May 14 22:25:08 2017
######################################################################

TEMPLATE = app
TARGET = scripts
INCLUDEPATH += .

# Input
HEADERS += ShopPy/dist/main.app/Contents/Resources/include/python3.5m/pyconfig.h \
           ShopPy/dist/main.app/Contents/Frameworks/Python.framework/Versions/3.5/include/python3.5m/pyconfig.h \
           ShopPy/dist/main.app/Contents/Frameworks/Python.framework/Versions/Current/include/python3.5m/pyconfig.h
FORMS += tuts4pyside/about_box/about.ui \
         tuts4pyside/quit_prog/quitter.ui \
         tuts4pyside/show_licence/licence.ui \
         tuts4pyside/combine_bits/designer/combine.ui \
         "Pyside Examples/Examples/mobility/audiodevices/audiodevicesbase.ui" \
         "Pyside Examples/Examples/mobility/publish-subscribe/publisherdialog.ui" \
         "Pyside Examples/Examples/mobility/publish-subscribe/publisherdialog_hor.ui" \
         "Pyside Examples/Examples/mobility/publish-subscribe/subscriberdialog.ui" \
         "Pyside Examples/Examples/mobility/publish-subscribe/subscriberdialog_hor.ui" \
         "Pyside Examples/Examples/mobility/sysinfo/dialog.ui" \
         "Pyside Examples/Examples/mobility/sysinfo/dialog_landscape.ui" \
         "Pyside Examples/Examples/examples/animation/easing/form.ui" \
         "Pyside Examples/Examples/examples/demos/embeddeddialogs/embeddeddialog.ui" \
         "Pyside Examples/Examples/examples/designer/calculatorform/calculatorform.ui" \
         "Pyside Examples/Examples/examples/graphicsview/padnavigator/backside.ui" \
         "Pyside Examples/Examples/examples/itemviews/editabletreemodel/mainwindow.ui" \
         "Pyside Examples/Examples/examples/network/http/authenticationdialog.ui" \
         "Pyside Examples/Examples/examples/script/calculator/calculator.ui" \
         "Pyside Examples/Examples/examples/xmlpatterns/schema/schema.ui" \
         "Pyside Examples/Examples/mobility/battery-charge/battery-publisher/batterypublisher.ui"
SOURCES += simple.cpp i3/mail.sh.x.c qtquick/main.cpp
RESOURCES += tuts4pyside/truss/truss.qrc \
             tuts4pyside/truss3/truss.qrc \
             tuts4pyside/combine_bits/icons/combine.qrc \
             "Pyside Examples/Examples/mobility/sysinfo/examples.qrc" \
             "Pyside Examples/Examples/examples/animation/animatedtiles/animatedtiles.qrc" \
             "Pyside Examples/Examples/examples/animation/appchooser/appchooser.qrc" \
             "Pyside Examples/Examples/examples/animation/easing/easing.qrc" \
             "Pyside Examples/Examples/examples/animation/states/states.qrc" \
             "Pyside Examples/Examples/examples/demos/embeddeddialogs/embeddeddialogs.qrc" \
             "Pyside Examples/Examples/examples/demos/qtdemo/qtdemo.qrc" \
             "Pyside Examples/Examples/examples/desktop/systray/systray.qrc" \
             "Pyside Examples/Examples/examples/dialogs/classwizard/classwizard.qrc" \
             "Pyside Examples/Examples/examples/dialogs/configdialog/configdialog.qrc" \
             "Pyside Examples/Examples/examples/draganddrop/draggableicons/draggableicons.qrc" \
             "Pyside Examples/Examples/examples/draganddrop/draggabletext/draggabletext.qrc" \
             "Pyside Examples/Examples/examples/draganddrop/fridgemagnets/fridgemagnets.qrc" \
             "Pyside Examples/Examples/examples/draganddrop/puzzle/puzzle.qrc" \
             "Pyside Examples/Examples/examples/graphicsview/collidingmice/mice.qrc" \
             "Pyside Examples/Examples/examples/graphicsview/diagramscene/diagramscene.qrc" \
             "Pyside Examples/Examples/examples/graphicsview/dragdroprobot/dragdroprobot.qrc" \
             "Pyside Examples/Examples/examples/graphicsview/padnavigator/padnavigator.qrc" \
             "Pyside Examples/Examples/examples/itemviews/chart/chart.qrc" \
             "Pyside Examples/Examples/examples/itemviews/editabletreemodel/editabletreemodel.qrc" \
             "Pyside Examples/Examples/examples/itemviews/pixelator/images.qrc" \
             "Pyside Examples/Examples/examples/itemviews/pixelator/pixelator.qrc" \
             "Pyside Examples/Examples/examples/itemviews/puzzle/puzzle.qrc" \
             "Pyside Examples/Examples/examples/itemviews/simpletreemodel/simpletreemodel.qrc" \
             "Pyside Examples/Examples/examples/mainwindows/application/application.qrc" \
             "Pyside Examples/Examples/examples/mainwindows/dockwidgets/dockwidgets.qrc" \
             "Pyside Examples/Examples/examples/mainwindows/mdi/mdi.qrc" \
             "Pyside Examples/Examples/examples/mainwindows/sdi/sdi.qrc" \
             "Pyside Examples/Examples/examples/network/ftp/ftp.qrc" \
             "Pyside Examples/Examples/examples/opengl/textures/textures.qrc" \
             "Pyside Examples/Examples/examples/painting/basicdrawing/basicdrawing.qrc" \
             "Pyside Examples/Examples/examples/painting/svgviewer/svgviewer.qrc" \
             "Pyside Examples/Examples/examples/phonon/pyqplayer/qplayer.qrc" \
             "Pyside Examples/Examples/examples/richtext/syntaxhighlighter/syntaxhighlighter.qrc" \
             "Pyside Examples/Examples/examples/script/calculator/calculator.qrc" \
             "Pyside Examples/Examples/examples/tools/i18n/i18n.qrc" \
             "Pyside Examples/Examples/examples/tools/qtdemo/qtdemo.qrc" \
             "Pyside Examples/Examples/examples/widgets/tooltips/tooltips.qrc" \
             "Pyside Examples/Examples/examples/xmlpatterns/schema/schema.qrc" \
             "Pyside Examples/Examples/examples/hyperui/hyperuilib/resource/hyperui.qrc"
TRANSLATIONS += "Pyside Examples/Examples/examples/declarative/photoviewer/i18n/base.ts" \
                "Pyside Examples/Examples/examples/declarative/photoviewer/i18n/qml_fr.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_ar.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_cs.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_de.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_el.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_en.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_eo.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_fr.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_it.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_jp.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_ko.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_no.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_pt.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_ru.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_sv.ts" \
                "Pyside Examples/Examples/examples/tools/i18n/translations/i18n_zh.ts"
