######################################################################
# Automatically generated by qmake (3.1) Sun May 14 22:50:13 2017
######################################################################

TEMPLATE = app
TARGET = cpp
INCLUDEPATH += .

# Input
SOURCES += simple.cpp
QT += widgets
