######################################################################
# Automatically generated by qmake (3.1) Sun May 14 23:08:01 2017
######################################################################

TEMPLATE = app
TARGET = strings
INCLUDEPATH += .

# Input
SOURCES += basic.cpp
